# Generated by Django 2.2 on 2019-05-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AddField(
            model_name='collections',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MyUser'),
        ),
    ]
