# Generated by Django 2.2 on 2019-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190509_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='uicon',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/icons'),
        ),
    ]
